#!/usr/bin/env ruby
forge 'https://forgeapi.puppetlabs.com'

metadata

mod 'malmo-mcommons', git: 'https://github.com/malmostad/puppet-malmo.git'
mod 'attachmentgenie-locales'
mod 'jdowning-rbenv'
mod 'saz-memcached'
mod 'puppetlabs-mysql'
mod 'puppetlabs-java'
mod 'puppetlabs-apt'
mod 'elasticsearch-elasticsearch'
mod 'rodjek-logrotate'
mod 'puppetlabs-apache'
mod 'jfryman-nginx'
mod 'puppetlabs-ntp'
